using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DotNetFrameworkTestApp
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.4952
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------


    // 
    // This source code was auto-generated by wsdl, Version=2.0.50727.3038.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "ServiceSoap", Namespace = "https://ws.mcrewards.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ErrorResp))]
    public partial class MRSWebServices : Microsoft.Web.Services3.WebServicesClientProtocol//: System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback getCustomerVerificationOperationCompleted;

        private System.Threading.SendOrPostCallback getCustomerInformationOperationCompleted;

        private System.Threading.SendOrPostCallback getPointBalanceOperationCompleted;

        private System.Threading.SendOrPostCallback doRedemptionOperationCompleted;

        private System.Threading.SendOrPostCallback getCustomerVerificationCsOperationCompleted;

        private System.Threading.SendOrPostCallback doTravelRedemptionOperationCompleted;

        private System.Threading.SendOrPostCallback doCreditOperationCompleted;

        /// <remarks/>
        public MRSWebServices()
        {
            this.Url = "https://test.ws.mcrewards.com/MRSWebService/Service.asmx";
        }

        /// <remarks/>
        public event getCustomerVerificationCompletedEventHandler getCustomerVerificationCompleted;

        /// <remarks/>
        public event getCustomerInformationCompletedEventHandler getCustomerInformationCompleted;

        /// <remarks/>
        public event getPointBalanceCompletedEventHandler getPointBalanceCompleted;

        /// <remarks/>
        public event doRedemptionCompletedEventHandler doRedemptionCompleted;

        /// <remarks/>
        public event getCustomerVerificationCsCompletedEventHandler getCustomerVerificationCsCompleted;

        /// <remarks/>
        public event doTravelRedemptionCompletedEventHandler doTravelRedemptionCompleted;

        /// <remarks/>
        public event doCreditCompletedEventHandler doCreditCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/getCustomerVerification", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerVerificationResp getCustomerVerification(long sourceId, string bankAccountNumber, string language)
        {
            object[] results = this.Invoke("getCustomerVerification", new object[] {
                    sourceId,
                    bankAccountNumber,
                    language});
            return ((CustomerVerificationResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetCustomerVerification(long sourceId, string bankAccountNumber, string language, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getCustomerVerification", new object[] {
                    sourceId,
                    bankAccountNumber,
                    language}, callback, asyncState);
        }

        /// <remarks/>
        public CustomerVerificationResp EndgetCustomerVerification(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerVerificationResp)(results[0]));
        }

        /// <remarks/>
        public void getCustomerVerificationAsync(long sourceId, string bankAccountNumber, string language)
        {
            this.getCustomerVerificationAsync(sourceId, bankAccountNumber, language, null);
        }

        /// <remarks/>
        public void getCustomerVerificationAsync(long sourceId, string bankAccountNumber, string language, object userState)
        {
            if ((this.getCustomerVerificationOperationCompleted == null))
            {
                this.getCustomerVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerVerificationOperationCompleted);
            }
            this.InvokeAsync("getCustomerVerification", new object[] {
                    sourceId,
                    bankAccountNumber,
                    language}, this.getCustomerVerificationOperationCompleted, userState);
        }

        private void OngetCustomerVerificationOperationCompleted(object arg)
        {
            if ((this.getCustomerVerificationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerVerificationCompleted(this, new getCustomerVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/getCustomerInformation", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerInformationResp getCustomerInformation(long sourceId, string bankAccountNumber, string clientVirtualId, string verificationAnswer1, string verificationAnswer2, string verificationAnswer3, string verificationAnswer4, string verificationAnswer5)
        {
            object[] results = this.Invoke("getCustomerInformation", new object[] {
                    sourceId,
                    bankAccountNumber,
                    clientVirtualId,
                    verificationAnswer1,
                    verificationAnswer2,
                    verificationAnswer3,
                    verificationAnswer4,
                    verificationAnswer5});
            return ((CustomerInformationResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetCustomerInformation(long sourceId, string bankAccountNumber, string clientVirtualId, string verificationAnswer1, string verificationAnswer2, string verificationAnswer3, string verificationAnswer4, string verificationAnswer5, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getCustomerInformation", new object[] {
                    sourceId,
                    bankAccountNumber,
                    clientVirtualId,
                    verificationAnswer1,
                    verificationAnswer2,
                    verificationAnswer3,
                    verificationAnswer4,
                    verificationAnswer5}, callback, asyncState);
        }

        /// <remarks/>
        public CustomerInformationResp EndgetCustomerInformation(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerInformationResp)(results[0]));
        }

        /// <remarks/>
        public void getCustomerInformationAsync(long sourceId, string bankAccountNumber, string clientVirtualId, string verificationAnswer1, string verificationAnswer2, string verificationAnswer3, string verificationAnswer4, string verificationAnswer5)
        {
            this.getCustomerInformationAsync(sourceId, bankAccountNumber, clientVirtualId, verificationAnswer1, verificationAnswer2, verificationAnswer3, verificationAnswer4, verificationAnswer5, null);
        }

        /// <remarks/>
        public void getCustomerInformationAsync(long sourceId, string bankAccountNumber, string clientVirtualId, string verificationAnswer1, string verificationAnswer2, string verificationAnswer3, string verificationAnswer4, string verificationAnswer5, object userState)
        {
            if ((this.getCustomerInformationOperationCompleted == null))
            {
                this.getCustomerInformationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerInformationOperationCompleted);
            }
            this.InvokeAsync("getCustomerInformation", new object[] {
                    sourceId,
                    bankAccountNumber,
                    clientVirtualId,
                    verificationAnswer1,
                    verificationAnswer2,
                    verificationAnswer3,
                    verificationAnswer4,
                    verificationAnswer5}, this.getCustomerInformationOperationCompleted, userState);
        }

        private void OngetCustomerInformationOperationCompleted(object arg)
        {
            if ((this.getCustomerInformationCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerInformationCompleted(this, new getCustomerInformationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/getPointBalance", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public PointBalanceResp getPointBalance(long sourceId, string virtualId, string clientVirtualId)
        {
            object[] results = this.Invoke("getPointBalance", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId});
            return ((PointBalanceResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetPointBalance(long sourceId, string virtualId, string clientVirtualId, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getPointBalance", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId}, callback, asyncState);
        }

        /// <remarks/>
        public PointBalanceResp EndgetPointBalance(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((PointBalanceResp)(results[0]));
        }

        /// <remarks/>
        public void getPointBalanceAsync(long sourceId, string virtualId, string clientVirtualId)
        {
            this.getPointBalanceAsync(sourceId, virtualId, clientVirtualId, null);
        }

        /// <remarks/>
        public void getPointBalanceAsync(long sourceId, string virtualId, string clientVirtualId, object userState)
        {
            if ((this.getPointBalanceOperationCompleted == null))
            {
                this.getPointBalanceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPointBalanceOperationCompleted);
            }
            this.InvokeAsync("getPointBalance", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId}, this.getPointBalanceOperationCompleted, userState);
        }

        private void OngetPointBalanceOperationCompleted(object arg)
        {
            if ((this.getPointBalanceCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPointBalanceCompleted(this, new getPointBalanceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/doRedemption", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RedemptionResp doRedemption(long sourceId, string virtualId, string clientVirtualId, RedemptionInObject[] redemptionsIn)
        {
            object[] results = this.Invoke("doRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    redemptionsIn});
            return ((RedemptionResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindoRedemption(long sourceId, string virtualId, string clientVirtualId, RedemptionInObject[] redemptionsIn, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("doRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    redemptionsIn}, callback, asyncState);
        }

        /// <remarks/>
        public RedemptionResp EnddoRedemption(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RedemptionResp)(results[0]));
        }

        /// <remarks/>
        public void doRedemptionAsync(long sourceId, string virtualId, string clientVirtualId, RedemptionInObject[] redemptionsIn)
        {
            this.doRedemptionAsync(sourceId, virtualId, clientVirtualId, redemptionsIn, null);
        }

        /// <remarks/>
        public void doRedemptionAsync(long sourceId, string virtualId, string clientVirtualId, RedemptionInObject[] redemptionsIn, object userState)
        {
            if ((this.doRedemptionOperationCompleted == null))
            {
                this.doRedemptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoRedemptionOperationCompleted);
            }
            this.InvokeAsync("doRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    redemptionsIn}, this.doRedemptionOperationCompleted, userState);
        }

        private void OndoRedemptionOperationCompleted(object arg)
        {
            if ((this.doRedemptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doRedemptionCompleted(this, new doRedemptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/getCustomerVerificationCs", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CustomerVerificationCsResp getCustomerVerificationCs(long sourceId, string bankAccountNumber, string virtualId, string clientVirtualId, string language)
        {
            object[] results = this.Invoke("getCustomerVerificationCs", new object[] {
                    sourceId,
                    bankAccountNumber,
                    virtualId,
                    clientVirtualId,
                    language});
            return ((CustomerVerificationCsResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegingetCustomerVerificationCs(long sourceId, string bankAccountNumber, string virtualId, string clientVirtualId, string language, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("getCustomerVerificationCs", new object[] {
                    sourceId,
                    bankAccountNumber,
                    virtualId,
                    clientVirtualId,
                    language}, callback, asyncState);
        }

        /// <remarks/>
        public CustomerVerificationCsResp EndgetCustomerVerificationCs(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CustomerVerificationCsResp)(results[0]));
        }

        /// <remarks/>
        public void getCustomerVerificationCsAsync(long sourceId, string bankAccountNumber, string virtualId, string clientVirtualId, string language)
        {
            this.getCustomerVerificationCsAsync(sourceId, bankAccountNumber, virtualId, clientVirtualId, language, null);
        }

        /// <remarks/>
        public void getCustomerVerificationCsAsync(long sourceId, string bankAccountNumber, string virtualId, string clientVirtualId, string language, object userState)
        {
            if ((this.getCustomerVerificationCsOperationCompleted == null))
            {
                this.getCustomerVerificationCsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCustomerVerificationCsOperationCompleted);
            }
            this.InvokeAsync("getCustomerVerificationCs", new object[] {
                    sourceId,
                    bankAccountNumber,
                    virtualId,
                    clientVirtualId,
                    language}, this.getCustomerVerificationCsOperationCompleted, userState);
        }

        private void OngetCustomerVerificationCsOperationCompleted(object arg)
        {
            if ((this.getCustomerVerificationCsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCustomerVerificationCsCompleted(this, new getCustomerVerificationCsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/doTravelRedemption", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TravelRedemptionResp doTravelRedemption(long sourceId, string virtualId, string clientVirtualId, string userId, TravelRedemptionInObject[] redemptionsIn)
        {
            object[] results = this.Invoke("doTravelRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    redemptionsIn});
            return ((TravelRedemptionResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindoTravelRedemption(long sourceId, string virtualId, string clientVirtualId, string userId, TravelRedemptionInObject[] redemptionsIn, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("doTravelRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    redemptionsIn}, callback, asyncState);
        }

        /// <remarks/>
        public TravelRedemptionResp EnddoTravelRedemption(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((TravelRedemptionResp)(results[0]));
        }

        /// <remarks/>
        public void doTravelRedemptionAsync(long sourceId, string virtualId, string clientVirtualId, string userId, TravelRedemptionInObject[] redemptionsIn)
        {
            this.doTravelRedemptionAsync(sourceId, virtualId, clientVirtualId, userId, redemptionsIn, null);
        }

        /// <remarks/>
        public void doTravelRedemptionAsync(long sourceId, string virtualId, string clientVirtualId, string userId, TravelRedemptionInObject[] redemptionsIn, object userState)
        {
            if ((this.doTravelRedemptionOperationCompleted == null))
            {
                this.doTravelRedemptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoTravelRedemptionOperationCompleted);
            }
            this.InvokeAsync("doTravelRedemption", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    redemptionsIn}, this.doTravelRedemptionOperationCompleted, userState);
        }

        private void OndoTravelRedemptionOperationCompleted(object arg)
        {
            if ((this.doTravelRedemptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doTravelRedemptionCompleted(this, new doTravelRedemptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://ws.mcrewards.com/doCredit", RequestNamespace = "https://ws.mcrewards.com/", ResponseNamespace = "https://ws.mcrewards.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public CreditResp doCredit(long sourceId, string virtualId, string clientVirtualId, string userId, Credit credit)
        {
            object[] results = this.Invoke("doCredit", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    credit});
            return ((CreditResp)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BegindoCredit(long sourceId, string virtualId, string clientVirtualId, string userId, Credit credit, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("doCredit", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    credit}, callback, asyncState);
        }

        /// <remarks/>
        public CreditResp EnddoCredit(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((CreditResp)(results[0]));
        }

        /// <remarks/>
        public void doCreditAsync(long sourceId, string virtualId, string clientVirtualId, string userId, Credit credit)
        {
            this.doCreditAsync(sourceId, virtualId, clientVirtualId, userId, credit, null);
        }

        /// <remarks/>
        public void doCreditAsync(long sourceId, string virtualId, string clientVirtualId, string userId, Credit credit, object userState)
        {
            if ((this.doCreditOperationCompleted == null))
            {
                this.doCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoCreditOperationCompleted);
            }
            this.InvokeAsync("doCredit", new object[] {
                    sourceId,
                    virtualId,
                    clientVirtualId,
                    userId,
                    credit}, this.doCreditOperationCompleted, userState);
        }

        private void OndoCreditOperationCompleted(object arg)
        {
            if ((this.doCreditCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doCreditCompleted(this, new doCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CustomerVerificationResp : ErrorResp
    {

        private string programNameField;

        private CustomerVerificationQuestion[] questionsField;

        /// <remarks/>
        public string programName
        {
            get
            {
                return this.programNameField;
            }
            set
            {
                this.programNameField = value;
            }
        }

        /// <remarks/>
        public CustomerVerificationQuestion[] questions
        {
            get
            {
                return this.questionsField;
            }
            set
            {
                this.questionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CustomerVerificationQuestion
    {

        private string questionField;

        private string codeField;

        private string answerField;

        /// <remarks/>
        public string question
        {
            get
            {
                return this.questionField;
            }
            set
            {
                this.questionField = value;
            }
        }

        /// <remarks/>
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        public string answer
        {
            get
            {
                return this.answerField;
            }
            set
            {
                this.answerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class Credit
    {

        private string redemptionIdField;

        private string referenceNumberField;

        private string creditDescriptionField;

        /// <remarks/>
        public string redemptionId
        {
            get
            {
                return this.redemptionIdField;
            }
            set
            {
                this.redemptionIdField = value;
            }
        }

        /// <remarks/>
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public string creditDescription
        {
            get
            {
                return this.creditDescriptionField;
            }
            set
            {
                this.creditDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class TravelRedemptionInObject
    {

        private string redemptionDescriptionField;

        private long rewardMatrixItemIdField;

        private long quantityField;

        private string referenceNumberField;

        private string redemptionComponentField;

        private decimal pointsRedeemedField;

        private long itemCountField;

        private decimal cashPaidField;

        private decimal feesField;

        private decimal componentTotalCashValueField;

        private string invoiceNumberField;

        /// <remarks/>
        public string redemptionDescription
        {
            get
            {
                return this.redemptionDescriptionField;
            }
            set
            {
                this.redemptionDescriptionField = value;
            }
        }

        /// <remarks/>
        public long rewardMatrixItemId
        {
            get
            {
                return this.rewardMatrixItemIdField;
            }
            set
            {
                this.rewardMatrixItemIdField = value;
            }
        }

        /// <remarks/>
        public long quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }

        /// <remarks/>
        public string redemptionComponent
        {
            get
            {
                return this.redemptionComponentField;
            }
            set
            {
                this.redemptionComponentField = value;
            }
        }

        /// <remarks/>
        public decimal pointsRedeemed
        {
            get
            {
                return this.pointsRedeemedField;
            }
            set
            {
                this.pointsRedeemedField = value;
            }
        }

        /// <remarks/>
        public long itemCount
        {
            get
            {
                return this.itemCountField;
            }
            set
            {
                this.itemCountField = value;
            }
        }

        /// <remarks/>
        public decimal cashPaid
        {
            get
            {
                return this.cashPaidField;
            }
            set
            {
                this.cashPaidField = value;
            }
        }

        /// <remarks/>
        public decimal fees
        {
            get
            {
                return this.feesField;
            }
            set
            {
                this.feesField = value;
            }
        }

        /// <remarks/>
        public decimal componentTotalCashValue
        {
            get
            {
                return this.componentTotalCashValueField;
            }
            set
            {
                this.componentTotalCashValueField = value;
            }
        }

        /// <remarks/>
        public string invoiceNumber
        {
            get
            {
                return this.invoiceNumberField;
            }
            set
            {
                this.invoiceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class RedemptionInObject
    {

        private System.DateTime redemptionDateField;

        private string redemptionDescriptionField;

        private long rewardMatrixItemIdField;

        private long quantityField;

        private string referenceNumberField;

        /// <remarks/>
        public System.DateTime redemptionDate
        {
            get
            {
                return this.redemptionDateField;
            }
            set
            {
                this.redemptionDateField = value;
            }
        }

        /// <remarks/>
        public string redemptionDescription
        {
            get
            {
                return this.redemptionDescriptionField;
            }
            set
            {
                this.redemptionDescriptionField = value;
            }
        }

        /// <remarks/>
        public long rewardMatrixItemId
        {
            get
            {
                return this.rewardMatrixItemIdField;
            }
            set
            {
                this.rewardMatrixItemIdField = value;
            }
        }

        /// <remarks/>
        public long quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public string referenceNumber
        {
            get
            {
                return this.referenceNumberField;
            }
            set
            {
                this.referenceNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CreditResult
    {

        private string redemptionIdField;

        private decimal totalPointsRedeemedField;

        private string creditRedemptionIdField;

        /// <remarks/>
        public string redemptionId
        {
            get
            {
                return this.redemptionIdField;
            }
            set
            {
                this.redemptionIdField = value;
            }
        }

        /// <remarks/>
        public decimal totalPointsRedeemed
        {
            get
            {
                return this.totalPointsRedeemedField;
            }
            set
            {
                this.totalPointsRedeemedField = value;
            }
        }

        /// <remarks/>
        public string creditRedemptionId
        {
            get
            {
                return this.creditRedemptionIdField;
            }
            set
            {
                this.creditRedemptionIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class TravelRedemptionOutObject
    {

        private decimal redemptionIdField;

        private decimal redemptionFeeAmtField;

        /// <remarks/>
        public decimal redemptionId
        {
            get
            {
                return this.redemptionIdField;
            }
            set
            {
                this.redemptionIdField = value;
            }
        }

        /// <remarks/>
        public decimal redemptionFeeAmt
        {
            get
            {
                return this.redemptionFeeAmtField;
            }
            set
            {
                this.redemptionFeeAmtField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CustomerAddress
    {

        private string address1Field;

        private string address2Field;

        private string address3Field;

        private string address4Field;

        private string cityField;

        private string stateField;

        private string postalCodeField;

        private string countryField;

        /// <remarks/>
        public string address1
        {
            get
            {
                return this.address1Field;
            }
            set
            {
                this.address1Field = value;
            }
        }

        /// <remarks/>
        public string address2
        {
            get
            {
                return this.address2Field;
            }
            set
            {
                this.address2Field = value;
            }
        }

        /// <remarks/>
        public string address3
        {
            get
            {
                return this.address3Field;
            }
            set
            {
                this.address3Field = value;
            }
        }

        /// <remarks/>
        public string address4
        {
            get
            {
                return this.address4Field;
            }
            set
            {
                this.address4Field = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string postalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class RedemptionOutObject
    {

        private long redemptionIdField;

        private double redemptionFeeAmtField;

        /// <remarks/>
        public long redemptionId
        {
            get
            {
                return this.redemptionIdField;
            }
            set
            {
                this.redemptionIdField = value;
            }
        }

        /// <remarks/>
        public double redemptionFeeAmt
        {
            get
            {
                return this.redemptionFeeAmtField;
            }
            set
            {
                this.redemptionFeeAmtField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CreditResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TravelRedemptionResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerVerificationCsResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RedemptionResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointBalanceResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerInformationResp))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CustomerVerificationResp))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class ErrorResp
    {

        private string returnMsgField;

        private int returnCodeField;

        /// <remarks/>
        public string returnMsg
        {
            get
            {
                return this.returnMsgField;
            }
            set
            {
                this.returnMsgField = value;
            }
        }

        /// <remarks/>
        public int returnCode
        {
            get
            {
                return this.returnCodeField;
            }
            set
            {
                this.returnCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CreditResp : ErrorResp
    {

        private decimal pointsAvailableField;

        private CreditResult[] creditResultsField;

        /// <remarks/>
        public decimal pointsAvailable
        {
            get
            {
                return this.pointsAvailableField;
            }
            set
            {
                this.pointsAvailableField = value;
            }
        }

        /// <remarks/>
        public CreditResult[] creditResults
        {
            get
            {
                return this.creditResultsField;
            }
            set
            {
                this.creditResultsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class TravelRedemptionResp : ErrorResp
    {

        private decimal pointTotalRemainingField;

        private TravelRedemptionOutObject[] redemptionsOutField;

        /// <remarks/>
        public decimal pointTotalRemaining
        {
            get
            {
                return this.pointTotalRemainingField;
            }
            set
            {
                this.pointTotalRemainingField = value;
            }
        }

        /// <remarks/>
        public TravelRedemptionOutObject[] redemptionsOut
        {
            get
            {
                return this.redemptionsOutField;
            }
            set
            {
                this.redemptionsOutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CustomerVerificationCsResp : ErrorResp
    {

        private string programNameField;

        private string coBrandIdField;

        private string virtualIdField;

        private char redeemerSwField;

        private CustomerVerificationQuestion[] verificationQuestionsField;

        private string firstNameField;

        private string lastNameField;

        private CustomerAddress customerAddressField;

        private decimal pointTotalField;

        private string[] authorizedUserField;

        private string[] secondaryAccountHolderField;

        /// <remarks/>
        public string programName
        {
            get
            {
                return this.programNameField;
            }
            set
            {
                this.programNameField = value;
            }
        }

        /// <remarks/>
        public string coBrandId
        {
            get
            {
                return this.coBrandIdField;
            }
            set
            {
                this.coBrandIdField = value;
            }
        }

        /// <remarks/>
        public string virtualId
        {
            get
            {
                return this.virtualIdField;
            }
            set
            {
                this.virtualIdField = value;
            }
        }

        /// <remarks/>
        public char redeemerSw
        {
            get
            {
                return this.redeemerSwField;
            }
            set
            {
                this.redeemerSwField = value;
            }
        }

        /// <remarks/>
        public CustomerVerificationQuestion[] verificationQuestions
        {
            get
            {
                return this.verificationQuestionsField;
            }
            set
            {
                this.verificationQuestionsField = value;
            }
        }

        /// <remarks/>
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public CustomerAddress customerAddress
        {
            get
            {
                return this.customerAddressField;
            }
            set
            {
                this.customerAddressField = value;
            }
        }

        /// <remarks/>
        public decimal pointTotal
        {
            get
            {
                return this.pointTotalField;
            }
            set
            {
                this.pointTotalField = value;
            }
        }

        /// <remarks/>
        public string[] authorizedUser
        {
            get
            {
                return this.authorizedUserField;
            }
            set
            {
                this.authorizedUserField = value;
            }
        }

        /// <remarks/>
        public string[] secondaryAccountHolder
        {
            get
            {
                return this.secondaryAccountHolderField;
            }
            set
            {
                this.secondaryAccountHolderField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class RedemptionResp : ErrorResp
    {

        private double pointTotalRemainingField;

        private RedemptionOutObject[] redemptionsOutField;

        /// <remarks/>
        public double pointTotalRemaining
        {
            get
            {
                return this.pointTotalRemainingField;
            }
            set
            {
                this.pointTotalRemainingField = value;
            }
        }

        /// <remarks/>
        public RedemptionOutObject[] redemptionsOut
        {
            get
            {
                return this.redemptionsOutField;
            }
            set
            {
                this.redemptionsOutField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class PointBalanceResp : ErrorResp
    {

        private double pointTotalField;

        /// <remarks/>
        public double pointTotal
        {
            get
            {
                return this.pointTotalField;
            }
            set
            {
                this.pointTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "https://ws.mcrewards.com/")]
    public partial class CustomerInformationResp : ErrorResp
    {

        private string programNameField;

        private double pointTotalField;

        private string virtualIdField;

        /// <remarks/>
        public string programName
        {
            get
            {
                return this.programNameField;
            }
            set
            {
                this.programNameField = value;
            }
        }

        /// <remarks/>
        public double pointTotal
        {
            get
            {
                return this.pointTotalField;
            }
            set
            {
                this.pointTotalField = value;
            }
        }

        /// <remarks/>
        public string virtualId
        {
            get
            {
                return this.virtualIdField;
            }
            set
            {
                this.virtualIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getCustomerVerificationCompletedEventHandler(object sender, getCustomerVerificationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getCustomerVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CustomerVerificationResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CustomerVerificationResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getCustomerInformationCompletedEventHandler(object sender, getCustomerInformationCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerInformationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getCustomerInformationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CustomerInformationResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CustomerInformationResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getPointBalanceCompletedEventHandler(object sender, getPointBalanceCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPointBalanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getPointBalanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public PointBalanceResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((PointBalanceResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void doRedemptionCompletedEventHandler(object sender, doRedemptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doRedemptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal doRedemptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RedemptionResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RedemptionResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void getCustomerVerificationCsCompletedEventHandler(object sender, getCustomerVerificationCsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCustomerVerificationCsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal getCustomerVerificationCsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CustomerVerificationCsResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CustomerVerificationCsResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void doTravelRedemptionCompletedEventHandler(object sender, doTravelRedemptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doTravelRedemptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal doTravelRedemptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public TravelRedemptionResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((TravelRedemptionResp)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    public delegate void doCreditCompletedEventHandler(object sender, doCreditCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal doCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public CreditResp Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((CreditResp)(this.results[0]));
            }
        }
    }

}